server:
  port: 9060


spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:paper-app-test;
    driverClassName: org.h2.Driver
    username: root
    password: "6084"

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html

#  web:
#    resources:
#      static-locations:

logging:
  level:
    org.springframework.web: trace